jobs:
  check-build:
    name: Gradle Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Fetch Sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Setup Gradle Dependencies Cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts')
          }}
        path: ~/.gradle/caches
    - continue-on-error: true
      name: Setup Gradle Wrapper Cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties')
          }}
        path: ~/.gradle/wrapper
    - continue-on-error: true
      name: Run tests
      run: ./gradlew --no-daemon clean jacocoTestReport
    - continue-on-error: true
      name: Report test coverage
      run: 'pip install --user codecov

        codecov

        '
    timeout-minutes: 15
  check-gradlewrapper:
    name: Gradle Wrapper
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Fetch Sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1
    timeout-minutes: 5
  check-lint:
    name: Lint
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Fetch Sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Setup Gradle Dependencies Cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts')
          }}
        path: ~/.gradle/caches
    - continue-on-error: true
      name: Setup Gradle Wrapper Cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties')
          }}
        path: ~/.gradle/wrapper
    - continue-on-error: true
      name: Spotless check
      run: ./gradlew spotlessCheck --no-daemon
    timeout-minutes: 5
name: ci
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
