jobs:
  publish-docs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Generate Javadoc
      run: javadoc @.javadoc || true
    - continue-on-error: true
      name: Deploy GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        clean: true
        dry-run: false
        folder: doc
        target-folder: api
        token: ${{ secrets.GITHUB_TOKEN }}
  release:
    outputs:
      current_tag: ${{ steps.tag.outputs.current_tag }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - continue-on-error: true
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - continue-on-error: true
      run: npm ci
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
name: release-automated
on:
  repository_dispatch:
    types: trigger-ga___release-automated.yml
